# Generated by Django 6.0.2 on 2026-02-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0002_alter_lecture_module_id_alter_lecture_order_and_more"),
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student_id",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENTS"},
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.accounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student_id", "course_id"),
                name="unique_accounts_enrollment_course_id",
            ),
        ),
    ]
