# Generated by Django 6.0.2 on 2026-02-27 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0001_initial"),
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="enrollment",
            name="unique_accounts_enrollment_course_id",
        ),
        migrations.RenameField(
            model_name="lectureprogress",
            old_name="compeleted",
            new_name="completed",
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("COMPLETED", "Completed")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student_id",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.accounts",
            ),
        ),
        migrations.AlterField(
            model_name="lectureprogress",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lectureprogress",
            name="enrollment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="enrollments.enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student_id", "course_id"), name="unique_student_enrollment"
            ),
        ),
    ]
