# Generated by Django 6.0.2 on 2026-02-27 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0001_initial"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="reviews",
            name="unique_accounts_reviews_course_id",
        ),
        migrations.AddField(
            model_name="review",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.accounts"
            ),
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="course_id",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="student_id",
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("student_id", "course_id"), name="unique_student_course_review"
            ),
        ),
        migrations.DeleteModel(
            name="Reviews",
        ),
    ]
