# Generated by Django 6.0.2 on 2026-02-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="module_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.module"
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="order",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="module",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="order",
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name="lecture",
            constraint=models.UniqueConstraint(
                fields=("module_id", "order"), name="unique_module_lecure_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("course_id", "order"), name="unique_course_module_order"
            ),
        ),
    ]
